name: Notify Commits

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
            curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}"\
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/BrunoGambim/TesteGAB/actions/workflows/updatedependencies.yml/dispatches \
            -d '{"ref":"dev","inputs":{}}'
